name: free-foil-hm
version: 0.0.1
github: "evermake/free-foil-hm"

extra-source-files:
  - README.md
  - grammar/hindley-milner.cf

synopsis: Hindley-Milner type system implementation powered by Free Foil.
category: Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/evermake/free-foil-hm#readme>

custom-setup:
  dependencies:
    base: ">= 4.11.0.0 && < 5.0"
    process: ">= 1.6.3.0"
    Cabal: ">= 2.4.0.1 && < 4.0"
    PyF:

build-tools:
  BNFC:bnfc: ">= 2.9.4.1"
  alex: ">= 3.2.4"
  happy: ">= 1.19.9"

dependencies:
  base: ">= 4.7 && < 5"
  array: ">= 0.5.3.0"
  free-foil: ">= 0.0.3"

ghc-options:
  - -Wall

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - HM.Parser.Test
        - HM.Parser.ErrM
        - HM.Parser.Skel

executables:
  repl:
    main: Repl.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-hm
