-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}

-- | The abstract syntax of language HM.

module HM.Parser.AbsHM where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

import qualified Data.Data    as C (Data, Typeable)
import qualified GHC.Generics as C (Generic)

data Exp
    = ETrue
    | EFalse
    | ENat Integer
    | EAdd Exp Exp
    | ESub Exp Exp
    | EIf Exp Exp Exp
    | EIsZero Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

