name: Build & Deploy Haddock

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Build Haddock
        run: stack haddock free-foil-hm

      - name: Detect Haddock path
        run: echo "HADDOCK_DIR_PATH=$(stack path --local-doc-root)" >> $GITHUB_ENV

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.HADDOCK_DIR_PATH }}

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
